"""
Stub for the auto-generated _python_packaging module.

In a full build environment this file is generated by the build system.
On the Neo we provide the minimum needed for runtime imports.
"""

import contextlib

PACKAGE_VERSION = "0.0.0-dev"


@contextlib.contextmanager
def flight_systems_context():
    """No-op context manager — paths are already configured via PYTHONPATH."""
    yield None
