"""The ZMD package provides a high level API for processing "Zipline Message Definition" files."""

import re
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    # This is an autogenerated module that doesn't exist in the source tree when mypy runs.
    _python_packaging: Any

# Modules in the same package must be locally imported
from . import _python_packaging
from .autogen_python import generate_python_code
from .errors import ZmdParseError, ZmdReferenceError, ZmdSyntaxError
from .parse import parse
from .parser_types import (
    ParsedZmd,
    ParsedZmdEnum,
    ParsedZmdImports,
    ParsedZmdName,
    ParsedZmdStruct,
    ParsedZmdStructField,
)
from .util import ZmdFieldType, ZmdNode

__version__ = _python_packaging.PACKAGE_VERSION
