"""
Stub for the auto-generated _python_packaging module.

In a full build environment this file is generated by the build system.
On the Neo (or any standalone deployment) we don't need the path
manipulation it normally provides — the launch script sets PYTHONPATH
so that tools.zmd and tools.messages are already importable.
"""

import contextlib


@contextlib.contextmanager
def flight_systems_context():
    """No-op context manager — paths are already configured via PYTHONPATH."""
    yield None
